### ISSUE TITLE
Unable to create "txId" for redeeming tokens on L2

### ISSUE THREAD

**Issue by kautukkundan** [OffchainLabs/arbitrum-classic#1229]
I am trying to transfer tokens from L1 to L2 in local environment (geth and local arb nodes) but I am unable to redeem the tokens on arbitrum side. The "deposit" transaction successfully happens on L1 and I can also see logs of the transaction coming over on arbitrum but when I try to redeem using `ArbRetryableTx.redeem` with computed txId it always reverts. 

I got the code for creating the TxID from `arb-ts` package. Please suggest some solution.

```typescript
const tx = await ethErc20Bridge.deposit(TEST_ERC20, to, tokenAmount, maxSubmissionCost, maxGas, gasPrice, "0x", {
    gasLimit: 210000,
    value: ethers.utils.parseEther("0.0005"),
  });

  // GET SEQ ID FROM EVENT DATA
  const depositRec = await tx.wait();

  const iface = ethErc20Bridge.interface;
  const event = iface.getEvent("DepositToken");
  const eventTopic = iface.getEventTopic(event);

  const logs = depositRec.logs.filter((log: any) => log.topics[0] === eventTopic);
  const logData = logs.map((log: any) => iface.parseLog(log).args);
  const seqNum = logData[0].seqNum;

  // GET REQ ID FROM SEQ ID
  const arbProvider = new ethers.providers.JsonRpcProvider("http://localhost:8547");
  const chainID = ethers.BigNumber.from((await arbProvider.getNetwork()).chainId);

  const bitFlipSeqNum = (seqNum: BigNumber) => {
    return seqNum.or(BigNumber.from(1).shl(255));
  };

  const reqID = ethers.utils.keccak256(
    ethers.utils.concat([
      ethers.utils.zeroPad(chainID.toHexString(), 32),
      ethers.utils.zeroPad(bitFlipSeqNum(seqNum).toHexString(), 32),
    ]),
  );

  // GET redeemID
  const txId = ethers.utils.keccak256(
    ethers.utils.concat([ethers.utils.zeroPad(reqID, 32), ethers.utils.zeroPad(BigNumber.from(0).toHexString(), 32)]),
  );
```

**Comment by DZGoldman** [comment]
hi @kautukkundan! glancing over this, it looks correct. 
2 qs:
- What value are you using for max submission cost (/ did you query for it directly)?
- What's the revert message?

**Comment by kautukkundan** [comment]
thanks for replying

I am using "1000000000" as maxSubmissionCost and below is the revert message 

<img width="1403" alt="Screenshot 2021-06-02 at 2 17 37 PM" src="https://user-images.githubusercontent.com/23727056/120449692-4c317400-c3ad-11eb-916d-53a220cf60c3.png">
