### ISSUE TITLE
Cant get the Arb local docker running smoothly

### ISSUE THREAD

**Issue by syerwin** [OffchainLabs/arbitrum-classic#1354]
Hi, i've encountered this errors when i tried to run the Arbitrum locally with docker 

![image](https://user-images.githubusercontent.com/1388816/124761991-971a4a80-df5c-11eb-9357-7a1e37986544.png)

i've follow step by step the developer guide manual, step to produce the errors above are : 
- git clone -b master https://github.com/offchainlabs/arbitrum.git
- cd arbitrum
- git submodule update --init --recursive
- yarn
- yarn build
- yarn docker:build:geth
- yarn docker:geth
- yarn demo:initialize --force
- yarn demo:deploy

------------------
and then i was trying to run the Pet Shop dApp Demo with no luck of success, 

![image](https://user-images.githubusercontent.com/1388816/124762542-34757e80-df5d-11eb-8f09-833c509d9013.png)

step to produce :
- git clone https://github.com/OffchainLabs/demo-dapp-pet-shop
- cd demo-dapp-pet-shop
- yarn
- truffle migrate --network arbitrum

i run it on : 

- Ubuntu 18.04.5 LTS
- Truffle v5.3.6 (core: 5.3.6)
- Node v10.16.3
- Docker 19.03.13

did i missed something ? i would be grateful if the demo can run at least. Thankyou

**Comment by eigmax** [comment]
Can you show the result of `docker ps`
