### ISSUE TITLE
`eth_getStorageAt` fails with invalid argument error

### ISSUE THREAD

**Issue by shuklaayush** [OffchainLabs/arbitrum-classic#1607]
RPC call:
```bash
curl https://arb1.arbitrum.io/rpc \
  -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"eth_getStorageAt","params":["0xe72ba9418b5f2ce0a6a40501fe77c6839aa37333","0x1","latest"],"id":1}' 
```

Running this fails with the following error:
```bash
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"invalid argument 1: json: cannot unmarshal hex string of odd length into Go value of type hexutil.Bytes"}}
```

I think this is because the second param (`position`) in eth_getStorageAt RPC call is parsed as `hexutil.Bytes` ([code](https://github.com/OffchainLabs/arbitrum/blob/master/packages/arb-rpc-node/web3/eth.go#L108)) which expects an even length hex-string. Though based on [this spec](https://eth.wiki/json-rpc/API#eth_getstorageat), the second param (`position`) is a QUANTITY and hence should have the most compact representation (i.e. can be either odd or even length).

The RPC call works if I change the position param from `"0x1"` to `"0x01"`
```bash
curl https://arb1.arbitrum.io/rpc \
  -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"eth_getStorageAt","params":["0xe72ba9418b5f2ce0a6a40501fe77c6839aa37333","0x01","latest"],"id":1}' 
```

I'd be happy to contribute a PR if this does turn out to be a bug.

**Comment by happypsyduck** [comment]
This is a bug as this may be the reason why Ganache forking doesn't work with Arbitrum yet

**Comment by shuklaayush** [comment]
Probably fixed via 76a5f7526d6a027f0911244fa60ed2eef2ca52b0

**Comment by happypsyduck** [comment]
It looks to be a fix in that pull request, but it has yet to be integrated into the mainnet rpc.

**Comment by shuklaayush** [comment]
I've been using a custom hardhat fork as a workaround. It gets the job done
https://github.com/shuklaayush/hardhat/tree/fix/arbitrum
