### ISSUE TITLE
Can't see internal tx on arbiscan when interacting with contracts

### ISSUE THREAD

**Issue by asa93** [OffchainLabs/arbitrum-classic#1700]
Hi

I interacted with a contract and sent ETH to it.

Due to a fee system, part of the amount was transferred from the contract to a third party address.

However I can't seem to find any trace of it on Arbiscan.
When I check the third party address I can see the amount but there is no transaction associated with it.

Do you know if it's possible to find this transaction ?

Arbitrum doesn't seem to behave like Ethereum in this case..

**Comment by markocuri** [comment]
I've also found the same behavior. On discord they said it should be implemented soon but I don't see a github issue for this beside this one.
