### ISSUE TITLE
How to build arbitrum rpc node

### ISSUE THREAD

**Issue by netquery** [OffchainLabs/arbitrum-classic#1777]
Does arbitrum have documentation for building an rpc node?

**Comment by unlimittt** [comment]
From sources: https://developer.offchainlabs.com/docs/installation
Ready Docker image: https://developer.offchainlabs.com/docs/running_node

**Comment by henry-hz** [comment]
The Makefile is commented, so if you run  yarn install:validator you will have only the avm compiled....
but go to packages/arb-rpc-node and make a 'go build cmd/arb-node/arb-node.go

The arb-rpc-node uses arb-util, arb-node-core and the other packages as a dependency.
A make file to build and run

```Makefile

build:
        go build -o bin/arb-cli cmd/arb-cli/arb-cli.go
        go build -o bin/arb-dev-node cmd/arb-dev-node/arb-dev-node.go
        go build -o bin/arb-dev-sequencer cmd/arb-dev-sequencer/arb-dev-sequencer.go
        go build -o bin/arb-node cmd/arb-node/arb-node.go


forwarder:
        ./bin/arb-node --l1.url=https://mainnet.infura.io/v3/your_key

agg:
        ./bin/arb-node --l1.url=https://mainnet.infura.io/v3/your_key \
                --node.type=aggregator

seq:
        ./bin/arb-node --l1.url=https://mainnet.infura.io/v3/your_key \
                --node.type=sequencer
```

@unlimittt I need help to understand how to start the inbox broadcast feeder websocket server.
