### ISSUE TITLE
Node syncing stats

### ISSUE THREAD

**Issue by haowang1013** [OffchainLabs/arbitrum-classic#1828]
Hi,

I'm currently running a local ARB node and it syncs fine. The only problem is that I have no idea how long it'll take for the node to be fully synced. The only status I get is eth.blockNumber but there's no way to know what the "latest" block is on the chain.

Is it possible to expose more syncing related stats like eth.syncing?
Also, I did some measurement and my node is syncing 600-900 blocks per minute on mainnet, but only 30-40 blocks on rinkeby, is this normal?

Thanks

**Comment by huahuayu** [comment]
I got same question, `eth_syncing` is not exists
```json
{"jsonrpc":"2.0","id":67,"error":{"code":-32601,"message":"the method eth_syncing does not exist/is not available"}}
```

but `eth_blockNumber` is ok, so you can compare the `eth_blockNumber` result vs https://arbiscan.io/ to estimate.

**Comment by trajan0x** [comment]
Would also love to see this implemented, appears to be a regression as of the nitro merge
