### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by xinxurockx** [OffchainLabs/arbitrum-classic#1940]
running the node by docker: docker run -d  -v /opt/arbitrum-mainnet/:/home/user/.arbitrum/mainnet -p 0.0.0.0:8547:8547 -p 0.0.0.0:8548:8548 offchainlabs/arb-node:v1.1.2-cffb3a0 --l1.url http://54.255.204.156:8545 --node.cache.allow-slow-lookup

after running few days.It killed by system:[1402892.687776] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/docker/09b3bc619f582aba64690a3300c3792f112b0dfb408fe29d0d8bee3a1fbc9934,task=arb-node,pid=16302,uid=1000
[1402892.688188] Out of memory: Killed process 16302 (arb-node) total-vm:19404988kB, anon-rss:15629080kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:32428kB oom_score_adj:0
[1402893.761015] oom_reaper: reaped process 16302 (arb-node), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

by the way.my hardware is 4cpu/16G memory.

**Comment by iameli** [comment]
Yep, I've encountered a similar thing after about five weeks of operation. Seems to be a memory leak somewhere in `offchainlabs/arb-node:v1.1.2-cffb3a0`. Is there a newer version out there?

**Comment by happypsyduck** [comment]
Same issue after running for about 10 days on a system with 32Gb RAM / 1TB NVMe SSD. What setup is the team using to avoid this issue and is there a memory leak as it appears to be so?

**Comment by jacques-martin10** [comment]
Same problem here, regularly happenning:

```
Apr  3 02:01:24 elitebook kernel: [285725.325293] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/docker/12f5dd7a3a1e51c36d8fbbf0ca33b7f556306db1bfe4959916905a5d4505b699,task=arb-node,pid=2199916,uid=1000
Apr  3 02:01:24 elitebook kernel: [285725.325357] Out of memory: Killed process 2199916 (arb-node) total-vm:7431316kB, anon-rss:6527960kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:13104kB oom_score_adj:0
```

**Comment by happypsyduck** [comment]
Similar here as well. Hopefully switch to Nitro will fix the issue.

**Comment by nuliknol** [comment]
#2463 
related but ignored by the dev team
this problem is caused by a memory leak, the memory leak must be in C++ code side
