### ISSUE TITLE
restart the node takes too long too start sync

### ISSUE THREAD

**Issue by xinxurockx** [OffchainLabs/arbitrum-classic#1942]
when i restart the node,it stuck reloading chain for hours. 
Here is the docker log 
{"level":"info","component":"configuration","l1url":"http://54.255.204.156:8545","chainid":"1","time":"2022-01-06T15:06:37Z","caller":"/home/user/arb-util/configuration/configuration.go:566","message":"connected to l1 chain"}
{"level":"info","component":"arb-node","chainaddress":"c12ba48c781f6e392b49db2e25cd0c28cd77531a","chainid":"a4b1","type":"forwarder","fromBlock":12525700,"time":"2022-01-06T15:06:37Z","caller":"/home/user/arb-rpc-node/cmd/arb-node/arb-node.go:195","message":"Launching arbitrum node"}
{"level":"info","component":"monitor","directory":"/home/user/.arbitrum/mainnet/db","time":"2022-01-06T15:06:57Z","caller":"/home/user/arb-node-core/monitor/monitor.go:54","message":"database opened"}
Reloading chain starting with timestamp 1641480418
Seeding cache
Last L2 block saved to database: 4412489

my ssd iops is 6000 but using iostat 1 -x to show the ssd usage was 100% with iops 1500 

iostat 1 -x

nvme1n1       1354.00   7264.00     0.00   0.00    0.56     5.36    0.00      0.00     0.00   0.00    0.00     0.00    0.00      0.00     0.00   0.00    0.00     0.00    0.76  99.20

**Comment by nuliknol** [comment]
1 and a half hours it takes for me, very fast server 64G RAM, 10000 random IOPs. 

But if you shut it down and restart after like half a day , it will take days because apparently it will start sync from block 0

**Comment by crypto-only** [comment]
"it will take days because apparently it will start sync from block 0"
I think this is not correct if you make the volume of container persistent even after container being deleted without the `-rm` in `docker run`

**Comment by crypto-only** [comment]
Why does reload consume so much time?
Current size of database is about 60GB, the read speed is 50MB/s, so it's about 20 minutes = 60000/50/60, but my node is still loading after 40 minutes.

**Comment by huahuayu** [comment]
same issue.

**Comment by hdiass** [comment]
Please do something regarding this team! This makes the whole operation totally bad 🙏

**Comment by UglyTroLL** [comment]
+1

**Comment by gzeoneth** [comment]
You can use ioping to test latency, anything above 100us will load slowly. If you need fast startup time you would need a fast gen4 nvme ssd.

**Comment by lsdbitrue** [comment]
@gzeoneth Hi, Do you have any recommended on aws? 

We're using ebs gp3 with 8000 iops, it still takes 5 hours to start the node.

**Comment by gzeoneth** [comment]
You are recommended to use the local storage of aws instances, ebs would be too slow.

**Comment by lsdbitrue** [comment]
Thanks @gzeoneth I think we have to choose infura or quick node services

**Comment by gzeoneth** [comment]
> Thanks @gzeoneth I think we have to choose infura or quick node services

https://developer.offchainlabs.com/docs/node_providers
