### ISSUE TITLE
eth_call doesn't return correct data when used with a deploy bytecode

### ISSUE THREAD

**Issue by stevenbg** [OffchainLabs/arbitrum-classic#2065]
Hello! I'm working on a bridge with 10 EVM networks and I've hit a problem with Arbitrum. We make use of deployless multicall [[1](https://insights.magmatic.xyz/posts/deployless-multicall/)][[2](https://github.com/indexed-finance/multicall)] contracts which rely on the result from executing init bytecode with eth_call. Let me illustrate with a basic example.

I have the following contract:
```
// SPDX-License-Identifier: MIT

pragma solidity 0.8.6;

contract Test {
    constructor() {}
}
```
which (Remix) compiles to this bytecode:
`0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220e953221439c0cdcf0eaabf39c9e1c6fe6d482cf1d6feed7625c329cc9922039c64736f6c63430008060033`

When I do an eth_call rpc call on EVM networks (ethereum, bsc, polygon, avalanche)
```
curl --location --request POST 'https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161' \
--header 'Content-Type: application/json' \
--data-raw '{
	"jsonrpc":"2.0",
	"method":"eth_call",
	"params":[{
		"data": "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220e953221439c0cdcf0eaabf39c9e1c6fe6d482cf1d6feed7625c329cc9922039c64736f6c63430008060033"
	}, "latest"],
	"id":1
}'
```
I get a proper response, where `result` is the runtime bytecode. That is implicitly returned from the constructor.
`{"jsonrpc":"2.0","id":1,"result":"0x6080604052600080fdfea2646970667358221220e953221439c0cdcf0eaabf39c9e1c6fe6d482cf1d6feed7625c329cc9922039c64736f6c63430008060033"}`

When I do it with Arbitrum:
```
curl --location --request POST 'https://arb1.arbitrum.io/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
	"jsonrpc":"2.0",
	"method":"eth_call",
	"params":[{
		"data": "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220e953221439c0cdcf0eaabf39c9e1c6fe6d482cf1d6feed7625c329cc9922039c64736f6c63430008060033"
	}, "latest"],
	"id":1
}'
```
I'm not sure what is this, but it has nothing to do with the bytecode (If I actually deploy the contract and do an eth_getCode, I get the correct runtime bytecode. I should get the same value here from eth_call)
`{"jsonrpc":"2.0","id":1,"result":"0x000000000000000000000000e01c10fd900939d1eab56ee373ea5e2bd4e2cfb3"}`

This is important, because deployless multicall contracts [make use of assembly return to manipulate the constructor return value](https://github.com/indexed-finance/multicall/blob/master/contracts/MultiCall.sol#L27), but in Arbitrum that value is handled in some different way and we can't get it in `result`.

**Comment by FeurJak** [comment]
I had similar issue but got it fixed. I'm using the embedded multicall method on Arbitrum: https://github.com/Defi4Bitcoin/EmbeddedMultiCall

Here's an example golang code that I'm using to fetch multiple token balances for an account: 

`
func CallBalanceOfMulticall(ctx context.Context, cl *ethclient.Client, Tokens *[]string, Account string, BlockNo *big.Int) ([]*big.Int, error) {

	// Get RPC from Client.
	var clientValue = reflect.ValueOf(cl).Elem()
	fieldStruct := clientValue.FieldByName("c")
	clientPointer := reflect.NewAt(fieldStruct.Type(), unsafe.Pointer(fieldStruct.UnsafeAddr())).Elem()
	rpcClient, _ := clientPointer.Interface().(*rpc.Client)

	_Balances := make([]*big.Int, len(*Tokens))

	data := "0x610020565b600060405190508061001557606090505b818101604052919050565b6000805a6101ab604051600482823980518060e01c905061004081610004565b95508086019450808387395050506060600484019350835160e01c600485019450845160f81c6001860195506100766060610004565b43815260014303406020820152604081016000885b8881101561018b57805160f81c8060201b831792505060008260201c141561014157600181019050805160601c601482019150815160e01c6004830192508281840193505a60008084846000888ff160018a14156100ff575a82036100f06004610004565b8160e01b815260048e019d5050505b6101096001610004565b8160f81b81526101196004610004565b3d60e01b81526101283d610004565b3d6000823e60058f019e503d8f019e5050505050505050505b60018260201c141561017757600181019050805160601c601482019150803161016a6020610004565b81815260208a0199505050505b63ffffffff8216915060018201915061008b565b508082526101996004610004565b5a880360e01b81526004870196508684f3"
	data_input_len := 9
	var _calls string = ""

	// Prep Data
	_ContractInputData := "70a08231" + common.HexToHash(Account).String()[2:]                                         // CallData
	calldata_size := AddZerosPadding(IntToHex(len(_ContractInputData)/2), 8-len(IntToHex(len(_ContractInputData)/2))) // 8 char calldata size

	for _, Token := range *Tokens {
		_Contract_Addr := AddZerosPadding(common.HexToAddress(Token).String()[2:], 40-len(common.HexToAddress(Token).String()[2:]))
		_SubStr := "00" + _Contract_Addr + calldata_size + _ContractInputData
		//log.Println("Token: ", Token, " _SubStr: ", _SubStr)
		data_input_len += (len(_SubStr) / 2)
		_calls += _SubStr
	}

	data_input_len_hex := AddZerosPadding(IntToHex(data_input_len), 8-len(IntToHex(data_input_len)))

	data += data_input_len_hex + "0000ffff" + "01" + _calls
	//log.Info("Data: ", data)
	//log.Infof("data_input_len: %d data_input_len_hex: %s  _str: %s", data_input_len, data_input_len_hex, _calls)

	EthCallObj := EthCallObj{
		From: Account,
		To:   "0x0000000000000000000000000000000000000111",
		Gas:  "0xffffffff",
	}

	EthCallCustomCode := map[string]EthCallCustomCode{
		"0x0000000000000000000000000000000000000111": EthCallCustomCode{
			Code: data,
		},
	}

	var EthCallResult string
	err := rpcClient.CallContext(context.Background(), &EthCallResult, "eth_call", EthCallObj, "0x"+BigIntToHex(BlockNo), EthCallCustomCode)
	if err != nil {
		log.Error("[CallBalanceOfMulticall] Unable to perform Multicall, err: ", err.Error())
		return nil, err
	}

	// Now parse the result
	//log.Println("EthCallResult: ", EthCallResult)
	if len(EthCallResult) > 0 {
		j := 0
		i := 202
		// Results are of the following structure
		// 2 char Successfu (01 or 00)
		// 00000020 --> 8 byte for len of return data, convert to int then * by 2 for char len
		// 8 char Gas (i.e. 00010116)
		// i.e. 010000002000000000000000000000000000000000000000000000000000000000000000000000320a
		for i < len(EthCallResult) {
			_len_ret, _ := strconv.ParseInt(EthCallResult[i+2:i+10], 16, 64)
			_return_size := int(_len_ret * 2)
			if EthCallResult[i:i+2] == "01" {
				if _return_size != 0 {
					_balance, s := big.NewInt(0).SetString(EthCallResult[i+10:i+10+_return_size], 16)
					if s {
						_Balances[j] = _balance
					} else {
						_Balances[j] = big.NewInt(0)
					}
				} else {
					_Balances[j] = big.NewInt(0)
				}
			} else {
				_Balances[j] = big.NewInt(0)
			}
			i += 10 + _return_size + 8
			j += 1
		}
	} else {
		log.Error("[CallBalanceOfMulticall] Empty Output")
		return nil, nil
	}
	return _Balances, nil }
`
