### ISSUE TITLE
Trying to Deploying

### ISSUE THREAD

**Issue by boxingcoder00** [OffchainLabs/arbitrum-classic#2596]
Keep getting this error despite having the appropriate key from metamask any ideas?still a beginner learning all this. thanks

<img width="672" alt="Screen Shot 2023-03-10 at 6 14 20 AM" src="https://user-images.githubusercontent.com/111091683/224302501-455a9468-6fe6-4e56-b45a-668da6a4b63e.png">

**Comment by TucksonDev** [comment]
Hi there!
This is the deprecated repo of the old "classic" Arbitrum tech stack, no longer maintained.
I'll close this issue now, but if you are still encountering issues, consider the following options:
- For issues related to node running we now have a dedicated page in our dev docs for [Troubleshooting errors](https://developer.arbitrum.io/node-running/troubleshooting-running-nodes), and we also provide support in the channel #noderunning in the official [Discord](https://discord.gg/arbitrum) server.
- For issues related to the node's codebase, feel free to open new tickets in the [Arbitrum Nitro](https://github.com/OffchainLabs/nitro) repository.
