### ISSUE TITLE
Timestamp manipulation

### ISSUE THREAD

**Issue by stackmoon39** [OffchainLabs/arbitrum-classic#2597]
Timestamp manipulation: There's a line with a warning about relying on time: block.timestamp.
 Be aware that block.timestamp can be manipulated by miners within a certain range

**Comment by TucksonDev** [comment]
Hi there!
This is the deprecated repo of the old "classic" Arbitrum tech stack, no longer maintained.
I'll close this issue now, but if you are still encountering issues, consider the following options:
- For issues related to node running we now have a dedicated page in our dev docs for [Troubleshooting errors](https://developer.arbitrum.io/node-running/troubleshooting-running-nodes), and we also provide support in the channel #noderunning in the official [Discord](https://discord.gg/arbitrum) server.
- For issues related to the node's codebase, feel free to open new tickets in the [Arbitrum Nitro](https://github.com/OffchainLabs/nitro) repository.
