### ISSUE TITLE
docker image failed to run?

### ISSUE THREAD

**Issue by jimlon-xyz** [OffchainLabs/arbitrum-classic#2599]
I have downloaded the snapshot file in advance and mapped it to this container, the docker contianer outout some error message

Usage of /usr/local/bin/nitro:
ERROR[04-04|05:01:04.755] error initializing database              err="no --init.* mode supplied and chain data not in expected directory"
ERROR[04-04|05:01:04.788] Error in block freeze operation          err="canonical hash missing, can't freeze block 0"

`docker run --privileged -it -v /data/arbitrum:/home/user/.arbitrum -v /arbitrum:/arbitrum -p 8547:8547 -p 8548:8548 offchainlabs/nitro-node:v2.0.12-65d4e7a --l1.url https://cloudflare-eth.com --l2.chain-id=42161 --http.api=net,web3,eth --http.corsdomain=* --http.addr=0.0.0.0 --http.vhosts=* --init.url="file:///arbitrum/nitro.tar"
`

**Comment by fomolabsdev** [comment]
Same problem here

```
INFO [04-06|16:12:17.219] Running Arbitrum nitro node              revision=v2.0.11-8e786ec vcs.time=2023-02-07T11:11:46-06:00
INFO [04-06|16:12:17.219] connected to l1 chain                    l1url=https://eth-mainnet.g.alchemy.com/v2/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx l1chainid=1
INFO [04-06|16:12:17.219] Allocated cache and file handles         database=/home/user/.arbitrum/arb1/nitro/l2chaindata cache=16.00MiB handles=16 readonly=true
INFO [04-06|16:12:17.257] Opened ancient database                  database=/home/user/.arbitrum/arb1/nitro/l2chaindata/ancient/chain readonly=true
INFO [04-06|16:12:17.257] extracting downloaded init archive       size=32002MB
INFO [04-06|16:17:32.597] Allocated cache and file handles         database=/home/user/.arbitrum/arb1/nitro/l2chaindata cache=16.00MiB handles=16
INFO [04-06|16:17:32.868] Opened ancient database                  database=/home/user/.arbitrum/arb1/nitro/l2chaindata/ancient/chain readonly=false
Usage of /usr/local/bin/nitro:
ERROR[04-06|16:17:32.872] error initializing database              err="no --init.* mode supplied and chain data not in expected directory"
ERROR[04-06|16:17:32.876] Error in block freeze operation          err="canonical hash missing, can't freeze block 0"
INFO [04-06|16:17:32.876] Freezer shutting down 
arbitrum-node-nitro-node-1 exited with code 1

```

`docker-compose.yaml` contents is:

```
version: '3.3'
services:
  nitro-node:
    network_mode: host
    image: 'offchainlabs/nitro-node:v2.0.11-8e786ec'
    user: 1000:1000
    restart: always
    stop_grace_period: 30s
    volumes:
      - '/home/$USER/arbitrum-node/data/:/home/user/.arbitrum'	
      - '/home/$USER/arbitrum-node/snapdata/:/arbitrum-node/snapdata/'
    ports:
      - '127.0.0.1:8547:8547'
      - '127.0.0.1:8548:8548'
    command:
    - --init.url=file:///arbitrum-node/snapdata/nitro.tar
    - --l1.url=https://eth-mainnet.g.alchemy.com/v2/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - --l2.chain-id=42161 
    - --http.api=net,web3,eth,debug 
    - --http.corsdomain=* 
    - --http.addr=0.0.0.0 
    - --http.vhosts=*
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
```

**Comment by adrie0** [comment]
> I have downloaded the snapshot file in advance and mapped it to this container, the docker contianer outout some error message
> 
> Usage of /usr/local/bin/nitro: ERROR[04-04|05:01:04.755] error initializing database err="no --init.* mode supplied and chain data not in expected directory" ERROR[04-04|05:01:04.788] Error in block freeze operation err="canonical hash missing, can't freeze block 0"
> 
> `docker run --privileged -it -v /data/arbitrum:/home/user/.arbitrum -v /arbitrum:/arbitrum -p 8547:8547 -p 8548:8548 offchainlabs/nitro-node:v2.0.12-65d4e7a --l1.url https://cloudflare-eth.com --l2.chain-id=42161 --http.api=net,web3,eth --http.corsdomain=* --http.addr=0.0.0.0 --http.vhosts=* --init.url="file:///arbitrum/nitro.tar" `

Hi @jimlon-xyz visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Official Support](https://github.com/OffchainLabs/nitro/issues/communityarbtrum.online)

**Comment by TucksonDev** [comment]
Hi there!
This is the deprecated repo of the old "classic" Arbitrum tech stack, no longer maintained.
I'll close this issue now, but if you are still encountering issues, consider the following options:
- For issues related to node running we now have a dedicated page in our dev docs for [Troubleshooting errors](https://developer.arbitrum.io/node-running/troubleshooting-running-nodes), and we also provide support in the channel #noderunning in the official [Discord](https://discord.gg/arbitrum) server.
- For issues related to the node's codebase, feel free to open new tickets in the [Arbitrum Nitro](https://github.com/OffchainLabs/nitro) repository.
