### ISSUE TITLE
newHeads subscription with goethereum throws error

### ISSUE THREAD

**Issue by 0x090909** [OffchainLabs/arbitrum-classic#2604]
```
blocksSubscriber, err := ethClient.SubscribeNewHead(context.Background(), blockHeaders)
if err != nil {
log.WithFields(log.Fields{"err": err}).Fatal("New heads subscription")
}
```

....

```

block, err := ethClient.BlockByHash(context.Background(), blockHead.Hash())
if err != nil {
log.WithFields(log.Fields{"err": err}).Error("BlockByHash")
continue
}
```
![Screenshot 2023-05-09 at 20 03 31](https://github.com/OffchainLabs/arbitrum/assets/16927059/7d2cb9e0-6b25-4229-b280-4d0fcb2edbba)

I always get the following error, I dont understand it should be campatible since its evm, why I still keep getting this error.

**Comment by adrie0** [comment]
Hi @0x090909 visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Official Support](https://github.com/OffchainLabs/nitro/issues/communityarbtrum.online)

**Comment by TucksonDev** [comment]
Hi there!
This is the deprecated repo of the old "classic" Arbitrum tech stack, no longer maintained.
I'll close this issue now, but if you are still encountering issues, consider the following options:
- For issues related to node running we now have a dedicated page in our dev docs for [Troubleshooting errors](https://developer.arbitrum.io/node-running/troubleshooting-running-nodes), and we also provide support in the channel #noderunning in the official [Discord](https://discord.gg/arbitrum) server.
- For issues related to the node's codebase, feel free to open new tickets in the [Arbitrum Nitro](https://github.com/OffchainLabs/nitro) repository.
